# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b_9xMiLBDXXJVjH4O2lQzgtJxd-jdaoq
"""

def preprocess_text(string:str):
    
    string=string.lower()
    punctuations = '''!()-[]{};:'"\<>/?@#$^&*_~+='''
    string=string.replace('’',"")
    string=string.replace('\n',"")
    for x in string.lower(): 
        if x in punctuations: 
            string = string.replace(x, "") 
    return string